server:
  port: 9527
spring:
  application:
    name: cloud-gateway-service
  cloud:
    gateway:
      routes:
        - id: payment_routh
          #uri: http://localhost:8081
          uri: lb://pay-provider
          predicates:
            - Path=/payment/get/**
      discovery:
        locator:
          enabled: true  #开启从注册中心动态生成路由的功能，用微服务名进行路由

eureka:
  instance:
    hostname: cloud_gateway_service
  client:
    service-url:
      defaultZone: http://eureka8090.com:8090/eureka
    register-with-eureka: true
    fetch-registry: true

