spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      #  路由规则
      routes:
        - id: order_route
          uri: lb://gateway-order   # 需要转发的地址
          # 断言规则，用于路由规则匹配
          predicates:
            - Path=/order-ser/order/**
            - CheckAuth=top
          filters:
            - StripPrefix=1  # 转发之前去除掉第一层路径
            - CheckAuth=top

    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
