eureka:
  client:
    # 注册到 eureka server
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka8090.com:8090/eureka,http://eureka8091.com:8091/eureka
  # 主机名称的配置
  instance:
    instance-id: pay-provider8081
    prefer-ip-address: true
    # Eureka客户端向服务端发送心跳的时间间隔，默认为30秒
    lease-renewal-interval-in-seconds: 30
    # Eureka服务端在收到最后一次心跳后等待时间上限，超时将剔除服务，默认为90秒
    lease-expiration-duration-in-seconds: 90
