server:
  port: 8089
spring:
  application:
    name: pay-provider-hystrix
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
    service-url:
      defaultZone: http://eureka8090.com:8090/eureka
